sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t cathyyfyang/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true cathyyfyang/sample-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2" ### AWS region of your choice
  app: "Sampledevopseb" ### Your EB App name
  env: "Sampledevopseb-env" ### Your EB App environment name
  bucket_name: "sampledocker-react-s3" ### S3 bucket name
  bucket_path: "sample" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "AKIAUXLNXF7GPGLMW3GJ"
  secret_access_key: "AFoMR/av/SpVi+2acAkrwx6xY3UlpKngPMx9sTaa"
